name: Unit-Test Ubuntu

on:
  workflow_dispatch:

jobs:
  unit_test_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
      
      - name: Install dependencies
        run: ./vcpkg/vcpkg install gtest

      - name: Build project
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/PrivateUnitTest/PrivateUnitTest/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
      
      - name: Test project
        run: ctest